#139: add examples to regexp in roll engine
Imaginary-Horizons-Productions/HorizonsBot pull request #140
Opened 2023-12-28 18:59 UTC by ntseng

Summary
-------
- add examples to regexp in roll engine

Local Tests Performed
---------------------
- [x] bot still turns on
- documentation only

Issue
-----
Closes #139

2023-12-28 19:07 UTC, SillySalamndr commented
Do we want to add examples for the cases from lines 197 to 209? Should that be a different task?

2023-12-29 04:34 UTC, ntseng commented
Whoops, missed those. I'll add them now.

2024-01-08 00:47 UTC, SillySalamndr requested changes
There's at least one comment on one of the comments (geez, that'll get confusing) that should be fixed, since it will cause confusion down the line. Everything else is good enough for our cases.

2024-01-08 00:47 UTC, SillySalamndr commented on source/engines/rollEngine.js
> +		} else if (/^1?u?l\[.*\]/.test(parsingString)) { //parse single list roll // 1l["a", "b", "c"], 1ul[a, b, c, d]
Having one of these examples leave out the 1 would make it clearer that it is technically optional for this form.

2024-01-08 00:47 UTC, SillySalamndr commented on source/engines/rollEngine.js
> +		} else if (/^\d+d(\%|\d+)[dk][lh]?\d+$/.test(parsingString)) { //parse multiple die with selection // 1d20dl, 2d4kh2
Adding an example for drop lowest would cover cases better

2024-01-08 00:47 UTC, SillySalamndr commented on source/engines/rollEngine.js
> +		} else if (/^\d+d(\%|\d+)$/.test(parsingString)) { //parse multiple die roll // 1d20 + 1d6
This case is not for addition, but is instead for rolling one or more dice of the same size. (Addition is handled by cases not found in this review.) This also means that the example(s) for this should include one that rolls more than one die of that size.

2024-01-08 00:47 UTC, SillySalamndr commented on source/engines/rollEngine.js
> +		} else if (/^\d+d(\%|\d+)$/.test(parsingString)) { //parse multiple die roll // 1d20 + 1d6
We really should fix this one, even if we decide against the other two.

2024-01-11 04:45 UTC, SillySalamndr approved these changes

2024-01-11 04:46 UTC, merged